- hosts: all
  gather_facts: true   

  vars:
    decidim_app_repository: "{{ git_root }}/{{ git_organization }}/{{ git_repository }}"
    decidim_app_directory: "{{ decidim_deployment_path }}/{{ app_repository }}"
        
  roles:
    - bump
