- name: NodeJS | Download NodeJS
  shell:
    cmd: curl -sL https://rpm.nodesource.com/setup_22.x | bash -
  become: true

- name: NodeJS | Install NodeJS
  dnf:
    name: nodejs
    state: present
  become: true