- name: Certbot | Install packages
  dnf:
    name:
    - certbot
    - python3-certbot-nginx
    state: latest
  become: true

- name: Certbot | Create SSL certificate
  shell: 
    cmd: "certbot run -n --nginx --agree-tos 
                      -d {{ decidim_host }}
                      -m  {{ certbot_email_address }} 
                      --redirect"
  become: true

- name: Certbot | Restart Nginx
  systemd:
    state: restarted
    name: nginx
  become: true

- name: Certbot | Add cron job for certbot renewal
  cron:
    name: Certbot automatic renewal.
    job: "/usr/bin/certbot renew --quiet"
    minute: 15
    hour: 3
  become: true