- name: Nginx | Install Nginx
  dnf:
    name: "@nginx:1.24"
    state: present
  become: true

- name: Nginx | Start and enable service Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Nginx | Set nginx.conf config

  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  become: true

- name: Nginx | Set vhost config
  template:
    src: templates/nginx-sites.j2
    dest: "/etc/nginx/conf.d/decidim.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0664"
  become: true

- name: Nginx | Add execution permission to decidim user
  shell:
    cmd: "chmod g+x,o+x {{ decidim_home_path }}/"
  become: true
