- name: Rbenv | Clone rbenv repo
  ansible.builtin.git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "{{ decidim_deployment_path }}/.rbenv"

- name: Rbenv | Set rbenv config 1/2
  lineinfile:
    path: "{{ decidim_deployment_path }}/.bashrc"
    line: export PATH="$HOME/.rbenv/bin:$PATH"
    state: present

- name: Rbenv | Set rbenv config 2/2
  lineinfile:
    path: "{{ decidim_deployment_path }}/.bashrc"
    line: eval "$(rbenv init -)"
    state: present

- name: Rbenv | Source .bashrc
  shell: 
    cmd: . {{ decidim_deployment_path }}/.bashrc
