- name: Yarn | Download and install yarn with shell script
  shell:
    cmd: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
  become: true

- name: Yarn | Install Yarn
  dnf:
    name: yarn
    state: latest
  become: true

- name: Yarn | Source .bashrc
  shell: 
    cmd: . {{ decidim_deployment_path }}/.bashrc
